# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=32)),
                ('red', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('id_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rgb.Routine'),
        ),
    ]
