# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rgb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='id_number',
        ),
        migrations.AddField(
            model_name='routine',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='command',
            name='cmd',
            field=models.CharField(choices=[('1', 'rgb'), ('0', 'power')], max_length=32),
        ),
    ]
