# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgb', '0002_auto_20160707_2117'),
    ]

    operations = [
    ]
